version: 2

formats: []

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: setuptools
      path: .
  system_packages: true

build:
  os: ubuntu-20.04
  extras:
    - rust==1.46
  apt_packages:
    - libopus-dev

sphinx:
   configuration: docs/conf.py
