name: Docs
on: [push, release]

jobs:
  notebooks:
    name: "Build the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python and Rust
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1

      - name: Enter venv
        run: |
          python -m venv venv
          source venv/bin/activate.sh

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r docs/requirements.txt
          python -m pip install -r requirements_dev.txt

      - name: Build with maturin
        run: |
          maturin develop

      - name: Build the docs
        run: |
          working-directory: docs
          make html

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}